name: 'ecommerce'
version: '1.0.0'
config-version: 2

profile: 'ecommerce'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  ecommerce:
    +persist_docs: yes
    +column_types:
      customer_id: integer
      product_id: integer
      order_id: integer
      order_date: date
      amount: float
