ecommerce:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: ecommerce_analytics
      threads: 4
      keyfile: /opt/airflow/config/gcp-service-account.json
      location: EU

config:
  schema: raw

models:
  ecommerce:
    +materialized: table

models.ecommerce.dev:
  +materialized: table
  +schema: raw
  +tags: [ "ecommerce" ]
  